### ISSUE TITLE
D205

### ISSUE THREAD

**Issue by jlonge4** [alexaryanfisher/Portfolio_WGU#7]
Hi Alexa, I thought the best way to ping you would be to just open an issue lol. Anyway, how did you force the pgadmin Generate ERD to give you a one to one relationship? Mine will not do anything but 1:M or M:M no matter what. Thanks in advance!

**Comment by alexaryanfisher** [comment]
No problem, honestly I could not find a method to do this. I actually left it as a one to many and when explaining, I just referenced what correct relationship and explained the limitations of the tool. For my ERD model visualization, I manually edited the connection.

**Comment by jlonge4** [comment]
@alexaryanfisher shoot I have spent forever trying to force it to work after having my evaluation returned over it. Thanks a ton!
